import Head from 'next/head'
import styles from '@/styles/index.module.css'
import HomePage from './Home/Home';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <main className={styles.main}>
        <HomePage />
      </main>
    </>
  )
}
